// @generated by expo-yarn-workspaces
import 'expo-dev-client';
import 'expo/build/Expo.fx';
import { activateKeepAwake } from 'expo-keep-awake';
import {AppRegistry} from 'react-native';
import registerRootComponent from 'expo/build/launch/registerRootComponent';
import {name as appName} from '../app.json';

import App from '../App';

if (__DEV__) {
  activateKeepAwake();
}

AppRegistry.registerComponent(appName, () => App);
